### ISSUE TITLE
Loading of wifi-tv page very heavyweight. 

### ISSUE THREAD

**Issue by imaginator** [project-isizwe/wifi-chat#14]
Loading the wifi-tv channel costs 17MB.

![screenshot 2015-05-21 13 05 16](https://cloud.githubusercontent.com/assets/469572/7747395/58d60418-ffba-11e4-8624-a2202c0d10f2.png)

**Comment by imaginator** [comment]
- Looks like it's loading the same moving resources multiple times.
- looks like the resource is still http... I thought we cleared this up with them and they would be SSL-ing the video CDN. 
- I've asked @Natalieprojectisizwe for a contact on Wifi-TV and will follow up with them.

**Comment by mrflix** [comment]
I just added a preload="metadata" attribute to the embedded videos in an attempt to prevent preloading. Thought it'd do that by default.
Maybe we have to be even harder using preload="none". But I think metadata shows important things like the length of the video.

**Comment by imaginator** [comment]
Thanks Felix. Any idea why it seems to be loading the same resource
multiple times? (At least that's what I think I'm seeing in the Network
debug view)

**Comment by mrflix** [comment]
The multiple video-loading happens because of unnecessary full re-rendering after asynchronously loading the display name (channel title) and the comment count. So when nothing is cached (worst case) the content and thus the videos get re-rendered 3 times all in all (initial, when the display name got loaded, when the comment count got loaded).

Fixed that by only re-rendering the display name and comment count respectively. I also set the video to `preload="none"`, after figuring that `preload="metadata"` on the `<video>` tag still costs 6 mb. Now its down to shy below 1 mb.

Well spotted Simon!

**Comment by imaginator** [comment]
Well Fixed Felix! :)

On 21 May 2015 at 15:10, Felix Niklas notifications@github.com wrote:

> The multiple video-loading happens because of unnecessary full
> re-rendering after asynchronously loading the display name (channel title)
> and the comment count. So when nothing is cached (worst case) the content
> and thus the videos get re-rendered 3 times all in all (initial, when the
> display name got loaded, when the comment count got loaded).
> 
> Fixed that by only re-rendering the display name and comment count
> respectively. I also set the video to preload="none", after figuring that
> preload="metadata" on the <video> tag still costs 6 mb. Now its down to
> shy below 1 mb.
> 
> Well spotted Simon!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/project-isizwe/wifi-chat/issues/14#issuecomment-104272018
> .

## 

Simon Tennant | CEO Buddycloud http://buddycloud.com | +49 17 8545 0880

**Comment by lloydwatkin** [comment]
Closed as fixed
